#!/bin/bash
#based on 'crep' script from Campbell Barton

OUT="/tmp/mktmp"
git branch --list | sort > $OUT

# Print text with line numbers
sed = $OUT | sed 'N;s/\n/ /'

echo -n "enter a number to edit > "
read -e LINE

if [ "$LINE" == "" ] ; then
    echo "nothing selected... exiting."
    exit 0
fi

LINE=$LINE"p" # 4 -> 4p - for sed
EDIT=$(cat $OUT | sed -n $LINE) # file to edit

rm $OUT

# Now change the branch
git checkout $EDIT
